### ISSUE TITLE
USER STORY: Access - Navbar Navigation

### ISSUE THREAD

**Issue by andrebraga7** [andrebraga7/quotme#1]
As a **user** I can **view a navbar** so that **I can navigate between pages**.

## Acceptance Criteria ##
- There is a navbar with links to other pages;
- The active link is highlighted;

## Tasks ##
- [x] Implement navbar layout;
- [x] Add template holder links;
- [x] Add an active class to the active link.
