### ISSUE TITLE
USER STORY: Discover Page - View List of Most Recent Quotes

### ISSUE THREAD

**Issue by andrebraga7** [andrebraga7/quotme#12]
As a **user** I can **view the most recent quotes** so that **I am up to date with the latest content.**

## Acceptance Criteria ##
- A list of most recent quotes is displayed to the user;
- When the user scrolls down the page, new quotes are automatically displayed.

## Tasks ##
- [x] Create the discover page;
- [x] Iterate through all quotes and display in a list;
- [x] Add infinite scroll capability to the list.
