### ISSUE TITLE
USER STORY: Discover Page - List Quotes by Selected Category

### ISSUE THREAD

**Issue by andrebraga7** [andrebraga7/quotme#13]
As a **user** I can **view quotes by categories** so that **I can view only what interests me.**

## Acceptance Criteria ##
- Category options are displayed on the top of the discover page;
- Clicking a category only displays quotes from the selected category.

## Tasks ##
- [ ] Add category options layout on the top of the discover page;
- [ ] Add logic to filter all quotes by the selected category;
- [ ] List the result of the filtered quotes.
