### ISSUE TITLE
USER STORY: Quote Page - Edit Quote

### ISSUE THREAD

**Issue by andrebraga7** [andrebraga7/quotme#18]
As a **quote owner** I can **edit the quote title and content** so that **I can make corrections.**

## Acceptance Criteria ##
- Quote owner can edit a quote title and content.

## Tasks ##
- [ ] Show the edit button only to the quote owner;
- [ ] Add logic to handle the on click event;
- [ ] Create the quote edit form;
- [ ] Handle the on submit of the edit form and update the quote.
