### ISSUE TITLE
USER STORY: Quote Page - Edit a Comment

### ISSUE THREAD

**Issue by andrebraga7** [andrebraga7/quotme#22]
As a **logged in user** I can **edit a comment** so that **I can update the content.**

## Acceptance Criteria ##
- The comment owner can view an edit button;
- When the comment owner clicks the edit button a form with the loaded content appears;
- When the user clicks the submit button the comment content is updated.

## Tasks ##
- [x] Add an edit button to the comment owner;
- [x] Load the edit form with the comment data;
- [x] Add logic to handle the submit event and update the comment.
