### ISSUE TITLE
USER STORY: Quote Page - Reply to a Comment

### ISSUE THREAD

**Issue by andrebraga7** [andrebraga7/quotme#25]
As a **logged in user** I can **reply to a comment** so that **I can continue a conversations.**

## Acceptance Criteria ##
- Logged in user can view a reply button on a comment;
- When user clicks the reply button a reply form appears;
- User can submit and create a reply to a comment.

## Tasks ##
- [x] Add a reply button to logged in users;
- [x] Create a reply form;
- [x] Handle the submit event and create a reply.
