### ISSUE TITLE
USER STORY: Quote Page - Edit a Reply

### ISSUE THREAD

**Issue by andrebraga7** [andrebraga7/quotme#26]
As a **logged in user** I can **edit a reply** so that **I can update the content.**

## Acceptance Criteria ##
- Reply owner can view an edit button;
- When the edit button is clicked an edit form with the reply content appears;
- User can submit and update a reply.

## Tasks ##
- [x] Add an edit button to the reply owner;
- [x] Load the reply form with the reply content;
- [x] Add logic to handle the submit event and edit the reply.
