### ISSUE TITLE
USER STORY: Profile Page - View User Quotes

### ISSUE THREAD

**Issue by andrebraga7** [andrebraga7/quotme#30]
As a **user** I can **view all quotes by a specific user** so that **I can catch up on their content.**

## Acceptance Criteria ##
- Profile page lists all the quotes from a given user.

## Tasks ##
- [x] Fetch all quotes from a profile;
- [x] List all quotes for that profile;
- [x] Add infinite scroll to the list.
