### ISSUE TITLE
USER STORY: Profile Page - Follow or Unfollow

### ISSUE THREAD

**Issue by andrebraga7** [andrebraga7/quotme#31]
As a **logged in user** I can **follow or unfollow a user** so that **I can view or remove quotes created by them in my feed.**

## Acceptance Criteria ##
- Logged in user can click the follow or unfollow button;
- The followers and following counts are updated accordingly;

## Tasks ##
- [x] Display follow button if user is not following a profile;
- [x] Display unfollow button if user is following a profile;
- [x] Add logic to handle the on click event to add or remove a user from following a profile.
