### ISSUE TITLE
USER STORY: Profile Page - Edit Profile

### ISSUE THREAD

**Issue by andrebraga7** [andrebraga7/quotme#32]
As a **logged in user** I can **edit my profile** so that **I can update my bio or profile image.**

## Acceptance Criteria ##
- User can see an edit button on his profile page;
- When the button is clicked the edit profile form loads with content;
- The user can update profile details.

## Tasks ##
- [x] Add an edit button to the profile owner's page;
- [x] Create the edit profile form;
- [x] Add logic to handle the submit event and update the profile content.
