### ISSUE TITLE
USER STORY: Profile Page - Change Username and Password

### ISSUE THREAD

**Issue by andrebraga7** [andrebraga7/quotme#33]
As a **logged in user** I can **change my username and password** so that **I can change my display name and keep my account safe.**

## Acceptance Criteria ##
- User can view the change username and change password buttons;
- When the user clicks the the change username button he is taken to the edit username form;
- When the user clicks the the change password button he is taken to the edit password form;
- Clicking the save button updated the username or password.

## Tasks ##
- [x] Add change username and password buttons to the owner's profile page;
- [x] Create the change username form;
- [x] Create the change password form;
- [x] Add logic to handle the submit event and update the username or password.
