### ISSUE TITLE
USER STORY: Quote - Add New Quote

### ISSUE THREAD

**Issue by andrebraga7** [andrebraga7/quotme#7]
As a **user** I can **add a quote** so that **I can share it with the community.**

## Acceptance Criteria ##
- User can add a new quote with all content.

## Tasks ##
- [x] Create the quote add page;
- [x] Add a post method to the API;
- [x] Link the page with the add quote button.
