### ISSUE TITLE
USER STORY: Quote - Available Authors Select List

### ISSUE THREAD

**Issue by andrebraga7** [andrebraga7/quotme#8]
As a **user** I can **start typing an author of a quote** so that I**t automatically loads available authors.**

## Acceptance Criteria ##
- When user starts typing an author it shows available authors list;
- Acceptance criteria 2
- Acceptance criteria 3

## Tasks ##
- [x] Retrieve all authors from the database;
- [x] Iterate and filter the authors list on change event of the authors field;
- [x] Load a selected author to the field.
